site: Paul Bricman
title: Paul Bricman
description: A common thread which weaves together various fragments of my identity into a unified whole.
googlewebfonts: Space+Grotesk:wght@400;500;700
lang: en-US
data-theme: dark # default theme "dark" | "light"

# URL settings
url: "https://paulbricman.com"
permalink: "https://paulbricman.com"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-redirect-from

collections:
  pages:
    output: true
    permalink: /:name
  reflections:
    output: true
    permalink: /reflections/:slug
  thoughtware:
    output: true
    permalink: /thoughtware/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false

feed:
  collections:
    reflections:
      path: "/reflections/feed.xml"
    thoughtware:
      path: "/thoughtware/feed.xml"